### PR TITLE
feat: add iOS

### PR DESCRIPTION
**Pull request by hansemannn**
Differences to Android so far:
- Not all fields are exposed, only `fingerprint` and `issuesByDName`. This is due to the fact that iOS does not offer these nice X509-certificate wrappers like Android, but only has the raw C accessors and only for some fields (macOS has better outputs, but that's unfortunately limited to macOS)
- There is no access to the parent http-proxy from within the security manager, therefore the `sslCheck` event is currently fired on the `securityManager` object. If Android could do the same, that would be awesome. Otherwise we need some difference between iOS and Android

Download binary: https://www.dropbox.com/s/0hw4gjiikb2bbbu/ti.sslcheck-iphone-1.0.0.zip?dl=1

### CODE REVIEW

**Comment by m1ga** [comment]
Thanks :+1:  I'll test it tomorrow. I've pushed an update to Android so we have parity for the event:

https://github.com/m1ga/ti.sslcheck/blob/main/example/app.js#L13

**Comment by hansemannn** [comment]
Thanks a lot! Then we can make the other properties Android-only for now, but have base support for both :)

**Comment by hansemannn** [comment]
Okay, I'm ready from my end!

**Comment by m1ga** [comment]
There is a lot of debug log like `[INFO]   Number of certificates: 3` still in there.
But the rest works fine 👍

**Comment by hansemannn** [comment]
Yep, thats from the native appcelerator.https module. I agree it can be removed

**Comment by hansemannn** [comment]
Ready now from my end

**Pull request merged**
